name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  build:
    strategy:
      max-parallel: 2
      matrix:
        # type: [iso, raw]
        type: [raw]
        arch: [x86_64-linux]
    name: build ${{ matrix.type }}-${{ matrix.arch }}
    runs-on: ubuntu-latest # matrix.arch
    steps:
      # - uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix build -L .#packages.${{ matrix.arch }}.${{ matrix.type }}
      - run: |
          pwd
          ls -la result
          ls -la /nix/store

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.type }}-${{ matrix.arch }}
      #     path: result/${{ matrix.config }}/nixos-*.${{ matrix.config }}

  # release:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-ubuntu-latest
  #         path: output

  #     - name: Download macOS artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-macos-latest
  #         path: output

  #     - name: Download Windows artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-windows-latest
  #         path: output

  #     - name: Create release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       with:
  #         tag_name: ${{ github.ref_name }}
  #         release_name: "Release ${{ github.ref_name }}"
  #         body: "Automated release for ${{ github.ref_name }}."
  #         draft: false
  #         prerelease: false

  #     - name: Upload artifacts to release
  #       uses: actions/upload-release-asset@v1
  #       with:
  #         upload_url: ${{ steps.create_release.outputs.upload_url }}
  #         asset_path: output/*
  #         asset_name: ${{ github.ref_name }}-artifacts.zip
  #         asset_content_type: application/zip
