name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  build:
    strategy:
      max-parallel: 2
      matrix:
        arch: [x86] # , arm ]
        configuration: [iso]
    name: build ${{ matrix.arch }}-${{ matrix.configuration }}
    runs-on: ubuntu-latest # matrix.arch
    steps:
      - name: free disk space
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build -L .#nixosConfigurations.${{ matrix.configuration }}-$${{ matrix.configuration }}.config.system.build.isoImage
      # - run: nix build -L .#nixosConfigurations.${{ matrix.configuration }}-$${{ matrix.configuration }}.config.system.build.toplevel
