name: iso

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 2
      matrix:
        config: [iso]
        arch: [x86] # , arm]
    name: build ${{ matrix.config }}-${{ matrix.arch }}
    runs-on: ubuntu-latest # matrix.arch
    steps:
      # - uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build -L .#nixosConfigurations.${{ matrix.config }}-${{ matrix.arch }}.config.system.build.isoImage
      # /nix/store/a1dzj0gpjlnqymbqpn5n5dsy3f63nq5h-nixos-25.05.20241128.970e93b-x86_64-linux.iso/iso/nixos-25.05.20241128.970e93b-x86_64-linux.iso
      - uses: actions/upload-artifact@v3
        with:
          name: iso # ${{ matrix.config }}-${{ matrix.arch }}
          path: result/iso/nixos-*.iso

  # release:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-ubuntu-latest
  #         path: output

  #     - name: Download macOS artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-macos-latest
  #         path: output

  #     - name: Download Windows artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-windows-latest
  #         path: output

  #     - name: Create release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       with:
  #         tag_name: ${{ github.ref_name }}
  #         release_name: "Release ${{ github.ref_name }}"
  #         body: "Automated release for ${{ github.ref_name }}."
  #         draft: false
  #         prerelease: false

  #     - name: Upload artifacts to release
  #       uses: actions/upload-release-asset@v1
  #       with:
  #         upload_url: ${{ steps.create_release.outputs.upload_url }}
  #         asset_path: output/*
  #         asset_name: ${{ github.ref_name }}-artifacts.zip
  #         asset_content_type: application/zip
